"""GitHub export service.

Pushes a GeneratedSite to a GitHub repo under the user's account.
Uses `gh` CLI (already authed as shekelstrong via GITHUB_TOKEN env).

The repo is created on first export as public, named after
`site.project_name`.
"""

from __future__ import annotations

import asyncio
import logging
import os
import shutil
import tempfile
from dataclasses import dataclass

from bot.services.site_generator import GeneratedSite

logger = logging.getLogger(__name__)


@dataclass
class GitHubResult:
    success: bool
    repo_url: str
    repo_full_name: str
    message: str


def _gh_cli_exists() -> bool:
    return shutil.which("gh") is not None


async def export_to_github(
    site: GeneratedSite, *, user: str = "shekelstrong"
) -> GitHubResult:
    """Create a GitHub repo and push the site code.

    Args:
        site: Generated project to push.
        user: GitHub user/org to own the repo. Default: shekelstrong.
              In Phase 1.5 this comes from the Supabase user record
              (user's own github_oauth_token).
    """
    if not _gh_cli_exists():
        return GitHubResult(
            success=False,
            repo_url="",
            repo_full_name="",
            message="gh CLI not available",
        )

    repo_name = site.project_name.lower().replace("_", "-")
    full_name = f"{user}/{repo_name}"

    with tempfile.TemporaryDirectory(prefix="buildo-gh-") as tmp:
        # Write all files
        for f in site.files:
            full = os.path.join(tmp, f.path)
            os.makedirs(os.path.dirname(full), exist_ok=True)
            with open(full, "w", encoding="utf-8") as fp:
                fp.write(f.content)

        # Create repo via gh
        proc = await asyncio.create_subprocess_exec(
            "gh",
            "repo",
            "create",
            full_name,
            "--public",
            "--source",
            tmp,
            "--remote",
            "origin",
            "--push",
            "--description",
            f"Generated by Buildo: {site.preview_summary[:80]}",
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )
        stdout, stderr = await asyncio.wait_for(proc.communicate(), timeout=120)
        if proc.returncode != 0:
            err = stderr.decode(errors="replace")[:500]
            # If repo already exists, just push
            if "already exists" in err.lower():
                logger.info("github.repo-exists, will push: %s", full_name)
                return await _push_existing(tmp, full_name, repo_name, site)
            return GitHubResult(
                success=False,
                repo_url="",
                repo_full_name=full_name,
                message=f"gh repo create failed: {err}",
            )

        return GitHubResult(
            success=True,
            repo_url=f"https://github.com/{full_name}",
            repo_full_name=full_name,
            message="repo created and pushed",
        )


async def _push_existing(
    tmp: str, full_name: str, repo_name: str, site: GeneratedSite
) -> GitHubResult:
    """Push to an existing repo (force overwrite with generated code)."""
    # Init git if not already, set remote, commit, push
    cmds = [
        ["git", "init", "-b", "main"],
        ["git", "config", "user.email", "buildo@buildo.ai"],
        ["git", "config", "user.name", "Buildo Bot"],
        ["git", "add", "-A"],
        ["git", "commit", "-m", f"buildo: regenerate {repo_name}"],
        ["git", "remote", "add", "origin", f"https://github.com/{full_name}.git"],
        ["git", "push", "-f", "origin", "main"],
    ]
    for cmd in cmds:
        proc = await asyncio.create_subprocess_exec(
            *cmd,
            cwd=tmp,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )
        stdout, stderr = await asyncio.wait_for(proc.communicate(), timeout=60)
        if proc.returncode != 0:
            return GitHubResult(
                success=False,
                repo_url="",
                repo_full_name=full_name,
                message=f"{' '.join(cmd)} failed: {stderr.decode()[:200]}",
            )
    return GitHubResult(
        success=True,
        repo_url=f"https://github.com/{full_name}",
        repo_full_name=full_name,
        message="pushed to existing repo",
    )
